[build-system]
requires = ["setuptools>=61", "wheel", "versioneer[toml]"]
build-backend = "setuptools.build_meta"

[project]
name = "panel_segmentation"
dynamic = ["version"]
description = "A package to segment solar panels from a satellite image and perform automated metadata extraction."
license = { text = "MIT" }
requires-python = ">=3.8"
keywords = [
    "photovoltaic",
    "solar",
    "analytics",
    "analysis",
    "performance",
    "PV",
    "satellite",
]
authors = [
    { name = "Kirsten Perry",       email = "kirsten.perry@nrel.gov" },
    { name = "Quyen Nguyen",        email = "nguyquye@oregonstate.edu" },
    { name = "Kevin Anderson",      email = "kevin.anderson@snl.gov" },
    { name = "Christopher Campos",  email = "chris.acampos@yahoo.com" },
    { name = "Ayobami Edun",        email = "aedun@ufl.edu" },
]
dependencies = [
    "opencv-python-headless==4.6.0.66",
    "numpy>=1.18.1",
    "scikit_image>=0.16.2",
    "matplotlib>=3.1.3",
    "requests>=2.22.0",
    "pandas>=1.1.4",
    "Pillow>=8.0.1",
    "scikit_learn>=0.23.2",
    "h5py>=2.10.0",
    "torch>=1.9.0",
    "torchvision>=0.10.0",
    "mmdet==3.3.0",
    "mmengine==0.10.7",
    "kornia",
    "scipy",
    "rasterio",
    "geopandas",
    "beautifulsoup4==4.12",
    "dash==2.6.0",
    "laspy[laszip]==2.5.4",
    "open3d==0.18.0",
    "pyarrow==17.0.0",
    "pyproj==3.5.0",
    "boto3>=1.37.38",
    "cfgrib>=0.9.15.0",
    "folium>=0.18.0",
    "simplekml>=1.3.6",
    "xarray>=2023.1.0",
]

[project.optional-dependencies]
doc = [
    "sphinx==5.0",
    "jinja2<3.1",
    "pydata-sphinx-theme==0.14.0",
    "ipython",
    "nbsphinx",
    "sphinx_copybutton",
]
test = [
    "pytest>=5.3.5",
]
optional = []

[project.urls]
Homepage = "https://github.com/NREL/Panel-Segmentation"

[tool.setuptools]
zip-safe = false
include-package-data = true
packages = ["panel_segmentation"]

[tool.setuptools.package-data]
panel_segmentation = [
    "panel_segmentation/examples/*",
    "panel_segmentation/tests/*",
    "panel_segmentation/models/VGG16Net_ConvTranpose_complete.h5",
    "panel_segmentation/models/VGG16_classification_model.h5",
    "panel_segmentation/models/object_detection_model.pth",
    "panel_segmentation/models/hail_config.py",
    "panel_segmentation/models/hail_model.pth",
    "panel_segmentation/models/post_hurricane_config.py",
    "panel_segmentation/models/post_hurricane_model.pth",
    "panel_segmentation/models/pre_hurricane_config.py",
    "panel_segmentation/models/pre_hurricane_model.pth",
    "panel_segmentation/models/sol_searcher_config.py",
    "panel_segmentation/models/sol_searcher_model.pth",
]

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "panel_segmentation/_version.py"
versionfile_build = "panel_segmentation/_version.py"
tag_prefix = "v"
parentdir_prefix = "panel_segmentation-"
